### ISSUE TITLE
How to disconnect smartphone?

### ISSUE THREAD

**Issue by brianjmurrell** [bjoernhoefer/iGrill_bbqmqtt#1]
Hi.

In your troubleshooting guide you say:

- Finally disconnect your smartphone from the iGrill and start the service/process (or device) again

What does that mean exactly?  How do I disconnect my smartphone from the iGrill?  There doesn't seem to be any "disconnect" functionality in the current version of the Android app.

**Comment by bjoernhoefer** [comment]
In the previous version it was possible to disconnect the iGrill - the current version must be "killed" via Android System Settings - in some cases disabling Bluetooth was helpful.

It would be much more better to do this via the bluetooth ability of https://github.com/kvantetore/igrill but I did never get it properly running... 

If you like - feel free to contribute some code :-)

**Comment by brianjmurrell** [comment]
Why do these steps:

  1. Start the Origianl iGrill app ( iOS | Android and connect it with your iGrill.
  1. Set an alarm (please refer to the apps manual how to do that) for any of the connected probes to an fantastic value (e.g. 500° Celsius in my case). This probe don't has to be connected the whole time - we also just need one alarm

need to be done?

**Comment by bjoernhoefer** [comment]
If you don't set an alarm the iGrill don't sends any updates if the temperature changes.

Maybe I'm wrong and Weber changed this setting with the new app but if you leave the iGrill shut down for a few minutes and power it up again - it won't send any updates to the connected devices...
