### ISSUE TITLE
temperature overflowing an 8 bit value

### ISSUE THREAD

**Issue by brianjmurrell** [bjoernhoefer/iGrill_bbqmqtt#2]
When the temp hits 256, it overflows and displays as "0", subsequently of course 257 is "1", 258 a "2" and so on.  This seems to be because `formatedData[0:len(formatedData)-4]` is only an 8-bit value:

```
Probe 1:  63 (Hex Value:  3f )
```

**Comment by bjoernhoefer** [comment]
never had such high tempemperatures - as I'm following the low and slow principle, but I can changed that.

Did you tried it with a higher value?

**Comment by bjoernhoefer** [comment]
what happens if you set printoutloud to true?

do you get anything i can try to "troubleshot"?

**Comment by brianjmurrell** [comment]
256F is not so far out of the range of "low and slow" but yes, generally I agree that's as high as I'd want to go for a smoke.  But I use my smoker/grill for more than just smoking.  I use it to roast also.

Additionally, I'm actually measuring a wide range of temperatures to calibrate another thermometer.

> what happens if you set printoutloud to true?

That's what I did to get the `Probe 1:  63 (Hex Value:  3f )` from the [first comment](https://github.com/bjoernhoefer/iGrill_bbqmqtt/issues/2#issue-284928252).

> do you get anything i can try to "troubleshot"?

Nothing other than what `printoutloud` gave me from the first comment.  I am happy to hack and patch as you need to help gather more information.

**Comment by bjoernhoefer** [comment]
The temperature is in Celsius, so 256 degree celsius is high :-)

I'll take a closer look at it this weekend or later...

**Comment by brianjmurrell** [comment]
Here, where I have mine set to Fahrenheit, it's in Fahrenheit.  256F even for a smoke is not terribly high.  :-)

**Comment by bjoernhoefer** [comment]
Please use the new "release" I forked - it works pretty nice.
