### ISSUE TITLE
trouble with igrill and Authenticating

### ISSUE THREAD

**Issue by chairman2s** [bjoernhoefer/iGrill_bbqmqtt#3]
I tried to connect a igrill mini but I got the error message below:
` sudo python monitor_igrill_v2.py
Authenticating...
encrypted device challenge: fb140a9c447ef3e5015b0af986878c3c
decrypted device challenge: 048d7b01305267338b7cc6fc58fcc2fd
Invalid device challenge`

any ideas...? 

sorry, but I could not find where to post issues on igrill...

**Comment by bjoernhoefer** [comment]
Sorry, but I have no idea - did you try -> https://github.com/bjoernhoefer/igrill
If that also don't work maybe https://github.com/onlywade/igrill can help

**Comment by chairman2s** [comment]
I did a much simpler solution. I found a igrill 2 on sale ;) Works perfectly
